### ISSUE TITLE
Typecho 1.1 (17.4.24) 兼容性问题？

### ISSUE THREAD

**Issue by lydasia** [jzwalk/JWPlayer#1]
从 Typecho 1.0(14.10.10) 升级到 Typecho 1.1(17.4.24) 后无法加载播放器了，只显示标签代码，试了几个别的播放器插件正常，换主题无效，LAMP环境。

**Comment by jzwalk** [comment]
的确1.1转义了尖括号，新版插件已经针对性地做了修复。
